### ISSUE TITLE
invalid example  in https://github.com/coldbox-modules/cbox-security/wiki/Sample-JSON-Rules

### ISSUE THREAD

**Issue by wpdebruin** [coldbox-modules/cbox-security#3]
I think the double backslashes in the sample code are incorrect
user\\.login will match user\.login and not user.login, so  trying to match an invalid event?

**Comment by lmajano** [comment]
we will redo the docs, so added to the list

**Comment by wpdebruin** [comment]
If you need any help with better documentation for this module, just let me know.
I am willing to help, and I think I have a very detailed understanding of the inner workings of this module now 😊 Followed al code to find out how things were organized.

Just wondering: why are you not using something like confluence for documentation? For opensource it is free and it has very nice tools like gliffy for flow diagrams and  UML.

Wil

Van: Luis Majano [mailto:notifications@github.com]
Verzonden: woensdag 14 maart 2018 16:59
Aan: coldbox-modules/cbox-security <cbox-security@noreply.github.com>
CC: Wil de Bruin | Site4U <wdb@site4u.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [coldbox-modules/cbox-security] invalid example in https://github.com/coldbox-modules/cbox-security/wiki/Sample-JSON-Rules (#3)


we will redo the docs, so added to the list

**Comment by lmajano** [comment]
Thanks Wil!!

We have created the repo now for the book and will soon port it over: github.com/ortus-docs/cbsecurity-docs

The reason we don't use confluence for docs is that gitbooks serves us better.  It allows us to have a github repo for it, accept pull requests, have continuous integration to build real mobile books and even send to amazon for publishing. I can't do that with Confluence easily.
